/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import dao.usuarioDAO;
import forms.FormCadastro;
import javax.swing.JOptionPane;
import conexao.*;
import java.sql.*;
import java.beans.Statement;

/**
 *
 * @author rodrigo
 */
public class FormLogin extends javax.swing.JFrame {

    private Conexao cnn;

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        Conexao objCon = new Conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_nvsenha = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_usuario.setBorder(null);
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 360, 30));

        txt_senha.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha.setBorder(null);
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 360, 30));

        btn_entrar.setBorder(null);
        btn_entrar.setContentAreaFilled(false);
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 430, 220, 50));

        btn_nvsenha.setBorder(null);
        btn_nvsenha.setContentAreaFilled(false);
        getContentPane().add(btn_nvsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 180, 30));

        btn_cadastrar.setBorder(null);
        btn_cadastrar.setContentAreaFilled(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 230, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\k2bro\\OneDrive\\Documentos\\NetBeansProjects\\SoftPay\\src\\resources\\entrar.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        FormCadastro fc = new FormCadastro();
        fc.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        usuarioDAO UsuarioDao = new usuarioDAO();
        
        Conexao cnx = new Conexao();
        Conexao con = (Conexao) cnx.getConexao();
        if(txt_usuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor digite o usuário!");
        } else if (txt_senha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor digite sua senha!");
        }else{
            try{
                cnx.getConexao();
                cnx.stmt = cnx.con.createStatement();
                String usuario = txt_usuario.getText();
                String senha = txt_senha.getText();
                
                String sql = "select * from usuario where nome = '?' and senha = '?'";
                PreparedStatement stmt = this.cnn.prepareStatement(sql);
                
                stmt.setString(1,usuario.toString());
                stmt.setString(2,senha.toString());
                ResultSet rs = stmt.executeQuery(sql);

            } catch(Exception e){
                System.out.println(e.getMessage());
            }
        }        
    }//GEN-LAST:event_btn_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_nvsenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
