/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Usuario;
import dao.usuarioDAO;
import forms.FormLogin;
import forms.FormCadastro;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class FormCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastro
     */
    public FormCadastro() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextPane();
        txt_email = new javax.swing.JTextPane();
        txt_cpf = new javax.swing.JTextPane();
        txt_senha = new javax.swing.JPasswordField();
        txt_cfsenha = new javax.swing.JPasswordField();
        cbx_tipo = new javax.swing.JComboBox<>();
        btn_cadastrar = new javax.swing.JButton();
        label_form = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nome.setBackground(new java.awt.Color(255, 255, 255));
        txt_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 220, 30));

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 220, 30));

        txt_cpf.setBackground(new java.awt.Color(255, 255, 255));
        txt_cpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 230, 30));

        txt_senha.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_senha.setForeground(new java.awt.Color(0, 0, 0));
        txt_senha.setBorder(null);
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 210, 30));

        txt_cfsenha.setBackground(new java.awt.Color(255, 255, 255));
        txt_cfsenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cfsenha.setForeground(new java.awt.Color(0, 0, 0));
        txt_cfsenha.setBorder(null);
        getContentPane().add(txt_cfsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 140, 20));

        cbx_tipo.setBackground(new java.awt.Color(158, 0, 255));
        cbx_tipo.setForeground(new java.awt.Color(255, 255, 255));
        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de usuário", "Cliente", "Vendedor" }));
        cbx_tipo.setBorder(null);
        getContentPane().add(cbx_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 170, 40));

        btn_cadastrar.setBorder(null);
        btn_cadastrar.setContentAreaFilled(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 650, 250, 60));

        label_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FormCadastro.png"))); // NOI18N
        getContentPane().add(label_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        String nome = txt_nome.getText();
        String email = txt_email.getText();
        int cpf = Integer.parseInt(txt_cpf.getText());
        String senha = txt_senha.getText();
        String cfsenha = txt_cfsenha.getText();
        String tipo = (String) cbx_tipo.getSelectedItem();
        
        Usuario usuario = new Usuario();
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setCpf((char) cpf);
        usuario.setSenha(senha);
        usuario.setTipo(tipo);
        
        usuarioDAO UsuarioDao = new usuarioDAO();
        UsuarioDao.inserir(usuario);
        
        JOptionPane.showMessageDialog(null, "Usuário criado!");
        
        FormLogin lc = new FormLogin();
        lc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormCadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JLabel label_form;
    private javax.swing.JPasswordField txt_cfsenha;
    private javax.swing.JTextPane txt_cpf;
    private javax.swing.JTextPane txt_email;
    private javax.swing.JTextPane txt_nome;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
